/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/clerk-webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clerk Webhook */
        post: operations["clerk_webhook_auth_clerk_webhook_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Profile */
        patch: operations["update_profile_auth_profile_patch"];
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Api Keys */
        get: operations["list_api_keys_api_keys_get"];
        put?: never;
        /** Create Api Key */
        post: operations["create_api_key_api_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Api Key */
        delete: operations["revoke_api_key_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invite User */
        post: operations["invite_user_admin_users_invite_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Org Users */
        get: operations["list_org_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Org User */
        delete: operations["remove_org_user_admin_users__user_id__delete"];
        options?: never;
        head?: never;
        /** Update Org User */
        patch: operations["update_org_user_admin_users__user_id__patch"];
        trace?: never;
    };
    "/admin/users/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Stats */
        get: operations["user_stats_admin_users_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Org Api Keys */
        get: operations["list_org_api_keys_admin_api_keys_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk User Action */
        post: operations["bulk_user_action_admin_users_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/api-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Org Api Key */
        delete: operations["revoke_org_api_key_admin_api_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/webhook-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Webhook Deliveries
         * @description Recent outgoing webhook delivery attempts for this org (Redis ring
         *     buffer with in-memory fallback), newest first. Records include event,
         *     ok/http_status, attempts, and error.
         */
        get: operations["list_webhook_deliveries_admin_webhook_deliveries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/replay/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay Request
         * @description Dry-run a stored request against the CURRENT org policy.
         *
         *     No LLM call, no token deduction, no new RequestLog row — the input
         *     guardrail is re-run against the policy as it stands today.
         *     Follow-up (not implemented): cap the size of full_prompt pulled per call
         *     and rate-limit this endpoint, matching the rest of /admin.
         */
        post: operations["replay_request_admin_replay__request_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat Stream
         * @description SSE streaming endpoint. Yields `data: {json}` events:
         *       {"type":"token",  "content":"..."}            — each LLM token
         *       {"type":"done",   "status":"delivered", ...}  — final metadata
         *       {"type":"blocked","status":"input_blocked"|"output_blocked", ...}
         *       {"type":"error",  "detail":"..."}             — backend failure
         *       {"type":"ping"}                               — keepalive every 15s
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/{request_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Feedback */
        post: operations["submit_feedback_chat__request_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_analytics_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/top-blocked-reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Top Blocked Reasons
         * @description Most frequent fired rules among blocked requests, with the most recent occurrence of each.
         */
        get: operations["top_blocked_reasons_analytics_top_blocked_reasons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User Breakdown
         * @description Per-user request + token breakdown for org admins.
         */
        get: operations["user_breakdown_analytics_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Logs
         * @description Paginated request log with status, keyword, date range, and backend filters.
         */
        get: operations["logs_analytics_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Logs
         * @description Download request logs as a CSV file.
         */
        get: operations["export_logs_analytics_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/false-positive-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * False Positive Candidates
         * @description Blocked requests that users later disputed — either via positive feedback
         *     (thumbs-up on a blocked request) or because the owner later added the rule
         *     to their always-allow overrides. Grouped by fired rule so you can spot the
         *     guardrails most likely throwing false positives.
         */
        get: operations["false_positive_candidates_analytics_false_positive_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy */
        get: operations["get_policy_policy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Policy */
        patch: operations["update_policy_policy_patch"];
        trace?: never;
    };
    "/policy/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Policy
         * @description Restore the org's policy to the system defaults.
         */
        post: operations["reset_policy_policy_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/policy/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diff Policy
         * @description Compare two policy blobs field by field. No DB write — pure comparison.
         *
         *     Nested structures inside the rule blobs (e.g. pii_patterns entries) are
         *     compared as whole values per top-level field, not recursively.
         */
        post: operations["diff_policy_policy_diff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/rejections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rejections */
        get: operations["get_rejections_skills_rejections_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/rejections/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Rejection
         * @description Record rejected access from git push, CLI, or CI (authenticated).
         */
        post: operations["report_rejection_skills_rejections_report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/rejections/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Rejection From Content
         * @description Web helper: submit skill content, auto-scan, and add only blocked findings
         *     into the rejected-access review queue.
         */
        post: operations["create_rejection_from_content_skills_rejections_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/rejections/{rejection_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Rejected Access */
        post: operations["resolve_rejected_access_skills_rejections__rejection_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skills/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Skill */
        post: operations["scan_skill_skills_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Billing Config */
        get: operations["billing_config_billing_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plans */
        get: operations["list_plans_billing_plans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get My Wallet */
        get: operations["get_my_wallet_billing_wallet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Purchases */
        get: operations["list_purchases_billing_purchases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Checkout */
        post: operations["start_checkout_billing_checkout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/billing/simulate-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Purchase
         * @description Local testing only — credits tokens without Stripe.
         */
        post: operations["simulate_purchase_billing_simulate_purchase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Org */
        get: operations["get_org_org_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Org */
        patch: operations["update_org_org_patch"];
        trace?: never;
    };
    "/org/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Org Data
         * @description Org-scoped audit export for admins. Paginated request logs joined to the
         *     owning user's email. Never exposes raw prompts, passwords, or key hashes.
         */
        get: operations["export_org_data_org_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/rotate-webhook-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate Webhook Secret
         * @description Generate a new HMAC-SHA256 secret used to sign guardrail webhooks.
         *     Shown exactly once — store it in your webhook receiver.
         */
        post: operations["rotate_webhook_secret_org_rotate_webhook_secret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/detailed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detailed Health */
        get: operations["detailed_health_health_detailed_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/breakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Breaker Health
         * @description Per-backend circuit breaker state (closed | open | half_open).
         */
        get: operations["breaker_health_health_breakers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vector/seed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Blocked Patterns */
        post: operations["seed_blocked_patterns_vector_seed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vector/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Similar */
        post: operations["query_similar_vector_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** APIKeyCreate */
        APIKeyCreate: {
            /** Name */
            name: string;
            /** Expires At */
            expires_at?: string | null;
            /**
             * Scopes
             * @default [
             *       "chat"
             *     ]
             */
            scopes: string[];
        };
        /**
         * APIKeyCreated
         * @description Returned only once at creation — includes the raw key.
         */
        APIKeyCreated: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Is Active */
            is_active: boolean;
            /** Total Requests */
            total_requests: number;
            /** Total Blocked */
            total_blocked: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Scopes
             * @default [
             *       "chat"
             *     ]
             */
            scopes: string[];
            /** Raw Key */
            raw_key: string;
        };
        /** APIKeyOut */
        APIKeyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Key Prefix */
            key_prefix: string;
            /** Is Active */
            is_active: boolean;
            /** Total Requests */
            total_requests: number;
            /** Total Blocked */
            total_blocked: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Expires At */
            expires_at: string | null;
            /**
             * Scopes
             * @default [
             *       "chat"
             *     ]
             */
            scopes: string[];
        };
        /** AdminInviteUser */
        AdminInviteUser: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
        };
        /** AdminUserStats */
        AdminUserStats: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Admin */
            is_admin: boolean;
            /** Is Active */
            is_active: boolean;
            /** Last Login */
            last_login: string | null;
            /** Tokens Balance */
            tokens_balance: number;
            /** Tokens Used */
            tokens_used: number;
            /** Total Requests */
            total_requests: number;
            /** Total Blocked */
            total_blocked: number;
        };
        /** AdminUserUpdate */
        AdminUserUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Is Admin */
            is_admin?: boolean | null;
        };
        /** AnalyticsDashboard */
        AnalyticsDashboard: {
            summary: components["schemas"]["UsageSummary"];
            /** Time Series */
            time_series: components["schemas"]["TimeSeriesPoint"][];
            /** Top Rules */
            top_rules: components["schemas"]["TopFiredRule"][];
            /**
             * Provider Usage
             * @default []
             */
            provider_usage: components["schemas"]["ProviderUsage"][];
            /**
             * Recent Suspicious
             * @default []
             */
            recent_suspicious: {
                [key: string]: unknown;
            }[];
            /** Recent Logs */
            recent_logs: {
                [key: string]: unknown;
            }[];
        };
        /** BillingCheckoutRequest */
        BillingCheckoutRequest: {
            /** Plan Slug */
            plan_slug: string;
        };
        /** BillingCheckoutResponse */
        BillingCheckoutResponse: {
            /** Checkout Url */
            checkout_url?: string | null;
            /** Purchase Id */
            purchase_id?: string | null;
            /** Message */
            message?: string | null;
        };
        /** BillingConfigOut */
        BillingConfigOut: {
            /** Billing Enabled */
            billing_enabled: boolean;
            /** Free Signup Tokens */
            free_signup_tokens: number;
            /** Stripe Configured */
            stripe_configured: boolean;
            /** Stripe Publishable Key */
            stripe_publishable_key?: string | null;
        };
        /** BillingPlanOut */
        BillingPlanOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Tokens */
            tokens: number;
            /** Price Cents */
            price_cents: number;
            /** Currency */
            currency: string;
            /** Description */
            description: string;
            /**
             * Popular
             * @default false
             */
            popular: boolean;
            /** Price Display */
            price_display: string;
        };
        /** BillingPurchaseOut */
        BillingPurchaseOut: {
            /** Id */
            id: string;
            /** Plan Slug */
            plan_slug: string;
            /** Tokens Granted */
            tokens_granted: number;
            /** Amount Cents */
            amount_cents: number;
            /** Currency */
            currency: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** BillingWalletOut */
        BillingWalletOut: {
            /** Balance Tokens */
            balance_tokens: number;
            /** Tokens Used Lifetime */
            tokens_used_lifetime: number;
            /** Tokens Purchased Lifetime */
            tokens_purchased_lifetime: number;
            /** Billing Enabled */
            billing_enabled: boolean;
            /**
             * Unlimited
             * @default false
             */
            unlimited: boolean;
        };
        /** BulkUserAction */
        BulkUserAction: {
            /**
             * Action
             * @description enable | disable | remove
             */
            action: string;
            /** User Ids */
            user_ids: string[];
        };
        /** ChatRequest */
        ChatRequest: {
            /** Prompt */
            prompt: string;
            /** Model */
            model?: string | null;
            /** Backend */
            backend?: string | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Max Tokens
             * @default 1024
             */
            max_tokens: number;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Request Id */
            request_id: string;
            /** Response */
            response: string | null;
            /** Status */
            status: string;
            input_guard: components["schemas"]["GuardrailResult"];
            output_guard: components["schemas"]["GuardrailResult"] | null;
            /** Latency Ms */
            latency_ms: number;
            /** Model */
            model: string;
            /** Backend */
            backend: string;
            /** Tokens Remaining */
            tokens_remaining?: number | null;
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Rating
             * @description 1 = thumbs up, -1 = thumbs down, 0 = neutral
             */
            rating: number;
            /** Comment */
            comment?: string | null;
        };
        /** GuardrailResult */
        GuardrailResult: {
            /** Passed */
            passed: boolean;
            /** Check */
            check: string;
            /** Reason */
            reason: string;
            /**
             * Reason Code
             * @default clean
             */
            reason_code: string;
            /**
             * Risk Score
             * @default 0
             */
            risk_score: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Message */
            message: string;
        };
        /** OrgOut */
        OrgOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** OrgUpdate */
        OrgUpdate: {
            /** Name */
            name: string;
        };
        /** PolicyDiffEntry */
        PolicyDiffEntry: {
            /** Field */
            field: string;
            /** Before */
            before?: unknown | null;
            /** After */
            after?: unknown | null;
        };
        /** PolicyDiffRequest */
        PolicyDiffRequest: {
            /** Policy A */
            policy_a: {
                [key: string]: unknown;
            };
            /** Policy B */
            policy_b: {
                [key: string]: unknown;
            };
        };
        /** PolicyOut */
        PolicyOut: {
            /** Input Rules */
            input_rules?: {
                [key: string]: unknown;
            } | null;
            /** Output Rules */
            output_rules?: {
                [key: string]: unknown;
            } | null;
            /** Topic Policy */
            topic_policy?: {
                [key: string]: unknown;
            } | null;
            /** Compliance Rules */
            compliance_rules?: {
                [key: string]: unknown;
            } | null;
            /** Llm Backend */
            llm_backend?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Rate Limit Rpm */
            rate_limit_rpm?: number | null;
            /** Rate Limit Rpd */
            rate_limit_rpd?: number | null;
            /** Org Id */
            org_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PolicyUpdate
         * @description Partial update — only send what you want to change.
         */
        PolicyUpdate: {
            /** Input Rules */
            input_rules?: {
                [key: string]: unknown;
            } | null;
            /** Output Rules */
            output_rules?: {
                [key: string]: unknown;
            } | null;
            /** Topic Policy */
            topic_policy?: {
                [key: string]: unknown;
            } | null;
            /** Compliance Rules */
            compliance_rules?: {
                [key: string]: unknown;
            } | null;
            /** Llm Backend */
            llm_backend?: string | null;
            /** Llm Model */
            llm_model?: string | null;
            /** Rate Limit Rpm */
            rate_limit_rpm?: number | null;
            /** Rate Limit Rpd */
            rate_limit_rpd?: number | null;
        };
        /** ProviderUsage */
        ProviderUsage: {
            /** Backend */
            backend: string;
            /** Model */
            model: string;
            /** Count */
            count: number;
            /** Tokens */
            tokens: number;
        };
        /** ReplayCurrentVerdict */
        ReplayCurrentVerdict: {
            /** Passed */
            passed: boolean;
            /** Check */
            check: string;
            /** Reason */
            reason?: string | null;
            /**
             * Reason Code
             * @default clean
             */
            reason_code: string;
            /**
             * Risk Score
             * @default 0
             */
            risk_score: number;
        };
        /** ReplayOriginalVerdict */
        ReplayOriginalVerdict: {
            /** Passed */
            passed: boolean;
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
        };
        /** ReplayResponse */
        ReplayResponse: {
            /** Request Id */
            request_id: string;
            original: components["schemas"]["ReplayOriginalVerdict"];
            current: components["schemas"]["ReplayCurrentVerdict"];
            /** Would Change Outcome */
            would_change_outcome: boolean;
            /** Note */
            note: string;
        };
        /**
         * RotatedWebhookSecret
         * @description New webhook signing secret — only ever returned to the caller once.
         */
        RotatedWebhookSecret: {
            /** Webhook Secret */
            webhook_secret: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SeedPatternsRequest */
        SeedPatternsRequest: {
            /**
             * Texts
             * @description Blocked text patterns to index for semantic matching
             */
            texts: string[];
        };
        /** SeedPatternsResponse */
        SeedPatternsResponse: {
            /** Indexed */
            indexed: number;
            /** Message */
            message: string;
        };
        /** SimilarityQuery */
        SimilarityQuery: {
            /** Text */
            text: string;
            /**
             * Top K
             * @default 3
             */
            top_k: number;
        };
        /** SkillFindingOut */
        SkillFindingOut: {
            /** Finding Key */
            finding_key: string;
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Check */
            check: string;
            /** Reason */
            reason: string;
            /** Reason Code */
            reason_code: string;
            /** Explanation */
            explanation: string;
            /** Line Number */
            line_number?: number | null;
            /**
             * Snippet
             * @default
             */
            snippet: string;
            /**
             * Risk Score
             * @default 0
             */
            risk_score: number;
            /**
             * Allowed By Override
             * @default false
             */
            allowed_by_override: boolean;
        };
        /** SkillOverridesIn */
        SkillOverridesIn: {
            /** Session Allow Keys */
            session_allow_keys?: string[];
            /** Always Allow Keys */
            always_allow_keys?: string[];
            /** Always Allow Reason Codes */
            always_allow_reason_codes?: string[];
        };
        /** SkillRejectionCreateIn */
        SkillRejectionCreateIn: {
            /** Content */
            content: string;
            /** Filename */
            filename?: string | null;
            /**
             * Source
             * @default web_manual
             */
            source: string;
            /** Rejection Summary */
            rejection_summary?: string | null;
            /** Content Preview */
            content_preview?: string | null;
        };
        /** SkillRejectionOut */
        SkillRejectionOut: {
            /** Id */
            id: string;
            /** Filename */
            filename: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Findings */
            findings: {
                [key: string]: unknown;
            }[];
            /** Rejection Summary */
            rejection_summary: string;
            /** Content Preview */
            content_preview: string | null;
            /** Resolved Action */
            resolved_action: string | null;
            /** Resolver Note */
            resolver_note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Resolved At */
            resolved_at: string | null;
        };
        /** SkillRejectionReportIn */
        SkillRejectionReportIn: {
            /** Filename */
            filename?: string | null;
            /**
             * Source
             * @default git_push
             */
            source: string;
            /** Rejection Summary */
            rejection_summary?: string | null;
            /** Content Preview */
            content_preview?: string | null;
            /** Findings */
            findings: components["schemas"]["SkillFindingOut"][];
        };
        /** SkillRejectionResolveIn */
        SkillRejectionResolveIn: {
            /**
             * Action
             * @description allow_once | allow_always | keep_rejected
             */
            action: string;
            /** Note */
            note?: string | null;
        };
        /** SkillScanRequest */
        SkillScanRequest: {
            /** Content */
            content: string;
            /** Filename */
            filename?: string | null;
            overrides?: components["schemas"]["SkillOverridesIn"] | null;
        };
        /** SkillScanResponse */
        SkillScanResponse: {
            /** Safe */
            safe: boolean;
            /** Risk Score */
            risk_score: number;
            /** Findings */
            findings: components["schemas"]["SkillFindingOut"][];
            /** Line Count */
            line_count: number;
            /** Char Count */
            char_count: number;
            /** Filename */
            filename?: string | null;
            /**
             * Blocked
             * @default false
             */
            blocked: boolean;
            /**
             * Agent May Continue
             * @default true
             */
            agent_may_continue: boolean;
            /**
             * Agent Status
             * @default ok
             */
            agent_status: string;
            /** Rejection Summary */
            rejection_summary?: string | null;
            /** Blocking Findings */
            blocking_findings?: components["schemas"]["SkillFindingOut"][];
            /** Overridden Findings */
            overridden_findings?: components["schemas"]["SkillFindingOut"][];
            /** Rejection Id */
            rejection_id?: string | null;
        };
        /** TimeSeriesPoint */
        TimeSeriesPoint: {
            /** Ts */
            ts: string;
            /** Total */
            total: number;
            /** Delivered */
            delivered: number;
            /** Blocked */
            blocked: number;
        };
        /** TopBlockedReason */
        TopBlockedReason: {
            /** Fired Rule */
            fired_rule: string;
            /** Count */
            count: number;
            /**
             * Last Occurred At
             * Format: date-time
             */
            last_occurred_at: string;
        };
        /** TopFiredRule */
        TopFiredRule: {
            /** Rule */
            rule: string;
            /** Count */
            count: number;
        };
        /** UpdateProfileRequest */
        UpdateProfileRequest: {
            /** Full Name */
            full_name?: string | null;
        };
        /** UsageSummary */
        UsageSummary: {
            /** Total Requests */
            total_requests: number;
            /** Delivered */
            delivered: number;
            /** Input Blocked */
            input_blocked: number;
            /** Output Blocked */
            output_blocked: number;
            /**
             * Rate Limited
             * @default 0
             */
            rate_limited: number;
            /** Error Count */
            error_count: number;
            /** Block Rate Pct */
            block_rate_pct: number;
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Total Tokens */
            total_tokens: number;
            /**
             * Estimated Cost Usd
             * @default 0
             */
            estimated_cost_usd: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /** Is Admin */
            is_admin: boolean;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Email Verified
             * @default false
             */
            email_verified: boolean;
            /** Org Id */
            org_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    clerk_webhook_auth_clerk_webhook_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    update_profile_auth_profile_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_api_keys_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyOut"][];
                };
            };
        };
    };
    create_api_key_api_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["APIKeyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_api_key_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invite_user_admin_users_invite_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminInviteUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_org_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    remove_org_user_admin_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_org_user_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_stats_admin_users_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserStats"][];
                };
            };
        };
    };
    list_org_api_keys_admin_api_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyOut"][];
                };
            };
        };
    };
    bulk_user_action_admin_users_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkUserAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_org_api_key_admin_api_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_webhook_deliveries_admin_webhook_deliveries_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    replay_request_admin_replay__request_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Api-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_chat__request_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_analytics_dashboard_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsDashboard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    top_blocked_reasons_analytics_top_blocked_reasons_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopBlockedReason"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_breakdown_analytics_users_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logs_analytics_logs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status_filter?: string | null;
                keyword?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                backend_filter?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_logs_analytics_export_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    false_positive_candidates_analytics_false_positive_candidates_get: {
        parameters: {
            query?: {
                days?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_policy_policy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    update_policy_policy_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_policy_policy_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyOut"];
                };
            };
        };
    };
    diff_policy_policy_diff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyDiffRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyDiffEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rejections_skills_rejections_get: {
        parameters: {
            query?: {
                /** @description pending | all | unblocked_once | unblocked_always | kept_rejected */
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRejectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_rejection_skills_rejections_report_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRejectionReportIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRejectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rejection_from_content_skills_rejections_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRejectionCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRejectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_rejected_access_skills_rejections__rejection_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rejection_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillRejectionResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillRejectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_skill_skills_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillScanResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    billing_config_billing_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingConfigOut"];
                };
            };
        };
    };
    list_plans_billing_plans_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPlanOut"][];
                };
            };
        };
    };
    get_my_wallet_billing_wallet_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingWalletOut"];
                };
            };
        };
    };
    list_purchases_billing_purchases_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingPurchaseOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_checkout_billing_checkout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillingCheckoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_purchase_billing_simulate_purchase_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BillingCheckoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_org_org_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
        };
    };
    update_org_org_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrgUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrgOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_org_data_org_export_get: {
        parameters: {
            query?: {
                days?: number;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotate_webhook_secret_org_rotate_webhook_secret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotatedWebhookSecret"];
                };
            };
        };
    };
    detailed_health_health_detailed_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    breaker_health_health_breakers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    seed_blocked_patterns_vector_seed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeedPatternsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedPatternsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_similar_vector_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimilarityQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}


// ─── Supplementary types ───────────────────────────────────────────────────────
// Shapes returned by the backend but not modeled in the OpenAPI spec (verified
// against app/routers/analytics.py and app/routers/chat.py).

export interface RequestLogItem {
  id: string;
  status: string;
  prompt_preview: string;
  full_prompt: null;
  model: string;
  backend: string;
  latency_ms: number;
  input_passed: boolean;
  output_passed: boolean;
  input_block_reason: string | null;
  output_block_reason: string | null;
  fired_rule: string | null;
  input_tokens: number;
  output_tokens: number;
  created_at: string;
  request_id: string;
}

export interface LogsResponse {
  total: number;
  page: number;
  page_size: number;
  items: RequestLogItem[];
}

export interface SuspiciousLogItem {
  id: string;
  status: string;
  prompt_preview: string;
  backend: string;
  fired_rule: string | null;
  reason: string | null;
  created_at: string;
}

export interface RecentLogItem {
  id: string;
  status: string;
  prompt_preview: string;
  model: string;
  backend: string;
  latency_ms: number;
  fired_rule: string | null;
  created_at: string;
}

export interface ChatFeedbackOut {
  rating: number;
  request_id: string;
}

export interface UserUsageStat {
  id: string;
  email: string;
  full_name: string | null;
  tokens_balance: number;
  tokens_used_lifetime: number;
  requests: number;
  blocked: number;
}

export interface ServiceHealth {
  status: string;
  latency_ms?: number;
  detail?: string;
  note?: string;
  http_status?: number;
}

export interface HealthDetailed {
  overall: string;
  database?: ServiceHealth;
  redis?: ServiceHealth;
  vectorstore?: ServiceHealth;
  llm_backends?: Record<string, ServiceHealth>;
  default_backend?: string;
  app_env?: string;
  billing_enabled?: boolean;
}
